### ISSUE TITLE
Cannot login to Evebox

### ISSUE THREAD

**Issue by cfmcarthur** [jasonish/experimental-suricata-training#1]
If I navigate to http://localhost:5636 I just have some symbols displayed like "�2". If I go to http://locaslhost:5636 the page displays but asks me for a username and password and I cannot see what they are from the notes.

**Comment by jasonish** [comment]
Kind of forgot about this repo, I don't think it'll see any really use - needs updates for the latest EveBox that is secure by default now.

**Comment by jasonish** [comment]
Fixed. Thanks for the notice.
